import Head from "next/head"

const head = () => {
  return(
    <Head>
      <title>Ukai Shota</title>
      <meta name="description" content="This site is portfolio of Ukai Shota" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default head;